spring:
  sql:
    init:
      platform: postgresql
  datasource:
    url: jdbc:postgresql://ec2-52-208-229-228.eu-west-1.compute.amazonaws.com:5432/deg2jmko2gqh9v
    username: fcusmbhclvvmkb
    password: c885ce0df924a61bf2c72765e7486a238a9f7ad34cf8ddb83e9c5ec9881f61ef
  jpa:
    hibernate:
      #      default_schema: public
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
